- name: bug
  color: d73a4a
  description: Something is not working
- name: enhancement
  color: a2eeef
  description: New feature or request
- name: dependencies
  color: 0366d6
  description: Dependency updates
- name: chore
  color: cfd3d7
  description: Maintenance task
- name: security
  color: b60205
  description: Security-related work
- name: good first issue
  color: 7057ff
  description: Good for first-time contributors
- name: help wanted
  color: 008672
  description: Extra attention is needed
